env:
  es6: true
  node: true
extends:
  - airbnb-base
  - 'plugin:prettier/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  prettier/prettier: 'error'
  import/extensions:
    - 'error'
    - 'ignorePackages'
    - { js: 'never', ts: 'never', json: 'never' }
  no-unused-vars:
    - 'warn'
    - argsIgnorePattern: '^_'
settings:
  import/resolver:
    node:
      extensions:
        - '.js'
        - '.ts'
        - '.json'
